### PR TITLE
changed markdown parser from cramdown to default (redcarpet)

### PR DESCRIPTION
**Pull request by arnehormann**
I don't have an easy way to check this, but it should fix syntax highlighting.

### CODE REVIEW

**Comment by arnehormann** [comment]
...aaaand unsuccessful, reverted :frowning: 
How does one get syntax highlighting in gh-pages like in the default github markdown view?!?
I wrongly thought kramdown was the only culprit, back to the drawing board.

**Comment by xaprb** [comment]
I thought about that too. Maybe we should ask on leTwitter, or examine
leStackOverflow.

**Comment by arnehormann** [comment]
I also had a look at [prismjs](http://prismjs.com) as a client side syntax highlighter. Let's see if my pull request to add Go syntax support gets through.

Anyway, this is really annoying. We should definitely ask. As your reach is a lot wider, I gracefully step back to let you do the asking :grinning:

Themewise, I had a look at [revel](http://robfig.github.io/revel/manual/index.html). Its site looks pretty neat. They don't get syntax-highlighting in the github markdown viewer, but it is there on the github pages. The file structure, theme and so on also look pretty decent. If we copy their site structure and change the content, we should be set.

I'll try to convert everything to revels way of doing things later, don't have the time right now.

**Comment by xaprb** [comment]
Revel's site looks nice. I'm fine with whatever. Not very picky (hence my
original choice of the first theme I found on Google search -- the
definition of not-very-picky).

**Pull request merged**
