### PR TITLE
another attempt - this time a copy of revel's tutorial section

### PR DESCRIPTION
**Pull request by arnehormann**

### CODE REVIEW

**Comment by xaprb** [comment]
That looks pretty good, except that the introductory page (index.md) is missing. If you add that into the table of contents does it appear?

**Comment by arnehormann** [comment]
Sorry, github just went bellyup for me with a unicorn warning. I'm on it now.

**Comment by arnehormann** [comment]
@robfig this is something we should probably have asked in advance...
We copied and minimally adapted revel's theme for the tutorial because it's the best github-pages use for Go we could find.
We don't have a "mentions" section yet, but as soon as we do, we'll add a notice.
Are you ok with this or should we change it?

**Comment by robfig** [comment]
No problem at all!  Glad you got some use out of it.  

FYI, you are missing out on Go syntax highlighting in your snippets.  You just need to use this pre block instead of the standard markdown quoting:

```
<pre class="prettyprint lang-go">
...
</pre>
```

**Comment by xaprb** [comment]
Thanks Rob!

**Pull request merged**
