### PR TITLE
Typo correction for #62

### PR DESCRIPTION
**Pull request by joshuaprunier**

### CODE REVIEW

**Comment by xaprb** [comment]
It's not a typo. http://golang.org/pkg/database/sql/#Rows.Err

**Comment by arnehormann** [comment]
@xaprb it's not a typo, but it can be misunderstood as one. The text directly below talks about `rows.Close()` and it says "Consider the following code" above - which doesn't contain `rows.Close()`.

**Comment by xaprb** [comment]
OK. Probably got all mixed up while I was rewriting a bunch of this. Will take a look later.

**Comment by joshuaprunier** [comment]
Ah, I think I see now. It looks like it may become 2 sections; Errors From Iterating Resultsets and Errors From Close. Bad pull request. My apologies.

**Comment by xaprb** [comment]
I pushed a branch with my proposed changes in #63. Review

**Comment by joshuaprunier** [comment]
Looks good to me. I was previously unaware of rows.Err() so I need to go back and modify some code. Thanks again for a great tutorial!

**Pull request closed without merging**
